In [54]:
import pandas as pd

In [59]:
results = pd.read_csv("/run/user/71447/gvfs/sftp:host=decore0.imag.fr,user=sfeirj/home/getalp/sfeirj/results/waves/results_wave_2")
results = results.drop(["syslen", "reflen", "score3", "score4", "my_mean", "my_sqrt", "my_diff_count"], axis=1)
results.head()

,lr,nb_layers,embed_dim,dropout,epoch,BLEU,score1,score2,brevity,ratio
0,0.0005,2,32,0.05,10,75.595702,83.334517,78.173636,0.996692,0.996698
1,0.0005,2,32,0.10,15,75.453576,83.248557,77.871952,0.999328,0.999328
2,0.0005,2,64,0.05,8,77.257204,84.313003,79.495931,1.000000,1.007931
3,0.0005,2,64,0.10,10,78.078855,85.158753,80.582677,0.995668,0.995678
4,0.0005,2,128,0.05,8,64.714533,71.743330,67.020982,1.000000,1.184302

In [60]:
results.sort_values(by=['score1'], ascending=False)

,lr,nb_layers,embed_dim,dropout,epoch,BLEU,score1,score2,brevity,ratio
3,0.0005,2,64,0.10,10,78.078855,85.158753,80.582677,0.995668,0.995678
2,0.0005,2,64,0.05,8,77.257204,84.313003,79.495931,1.000000,1.007931
0,0.0005,2,32,0.05,10,75.595702,83.334517,78.173636,0.996692,0.996698
1,0.0005,2,32,0.10,15,75.453576,83.248557,77.871952,0.999328,0.999328
5,0.0005,2,128,0.10,9,73.870825,81.572233,76.773559,0.991490,0.991526
10,0.0005,3,128,0.05,10,73.882612,81.296292,76.222414,1.000000,1.006345
12,0.0005,4,32,0.05,13,72.917440,81.086130,75.602485,0.997467,0.997470
6,0.0005,3,32,0.05,14,72.497085,80.911400,75.097894,1.000000,1.003137
15,0.0005,4,64,0.10,5,65.457811,80.752783,72.250426,0.950260,0.951457
9,0.0005,3,64,0.10,15,73.031739,80.585965,75.348651,1.000000,1.013203
16,0.0005,4,128,0.05,6,64.168416,80.238039,71.073435,0.952152,0.953261
13,0.0005,4,32,0.10,19,71.305885,80.159076,73.991283,1.000000,1.001628
8,0.0005,3,64,0.05,14,71.693068,79.166643,74.005569,1.000000,1.038489
11,0.0005,3,128,0.10,12,71.207656,78.647383,73.520604,1.000000,1.014837
7,0.0005,3,32,0.10,8,69.024579,78.329506,71.915255,1.000000,1.006699
14,0.0005,4,64,0.05,11,66.552540,78.141990,69.883535,1.000000,1.002217
17,0.0005,4,128,0.10,8,66.589252,77.605152,69.639071,1.000000,1.012661
4,0.0005,2,128,0.05,8,64.714533,71.743330,67.020982,1.000000,1.184302